/accelerator: "cpu"
/enable_checkpointing: True
max_epochs: 2 #2000
callbacks:
    - EarlyStopping:
        monitor: val_loss
        mode: min
        patience: 1

    - ModelCheckpoint:
        /dirpath: ${__exp__.project_folder}/out/models/
        /filename: best
        save_top_k: 1
        save_last: True
        monitor: val_loss
        mode: min